guests = ['Jinping', 'Turing', 'Darwin']
print("Hello " + guests[0] + ", could you have dinner with me?")
print("Hello " + guests[1] + ", could you have dinner with me?")
print("Hello " + guests[2] + ", could you have dinner with me?")
print("\n" + guests[2].title() + " can not have dinner with us.")
guests[2] = 'Sabrina'
print("Hello " + guests[2] + ", could you have dinner with me?")
print("\nWe found a bigger table!")
guests.insert(0, 'GeGe')
guests.insert(2, 'GaGa')
guests.append('GiGi')
print("Hello " + guests[0] + ", could you have dinner with me?")
print("Hello " + guests[1] + ", could you have dinner with me?")
print("Hello " + guests[2] + ", could you have dinner with me?")
print("Hello " + guests[3] + ", could you have dinner with me?")
print("Hello " + guests[4] + ", could you have dinner with me?")
print("Hello " + guests[5] + ", could you have dinner with me?")
print("\nSorry! Only two guests allowed.")
deleted_guests = guests.pop()
print("Sorry " + deleted_guests + ", I cannot have dinner with you.")
deleted_guests = guests.pop(0)
print("Sorry " + deleted_guests + ", I cannot have dinner with you.")
deleted_guests = guests.pop(1)
print("Sorry " + deleted_guests + ", I cannot have dinner with you.")
deleted_guests = guests.pop(1)
print("Sorry " + deleted_guests + ", I cannot have dinner with you.")
print("\n" + guests[0] + ", you are still invited!")
print(guests[1] + ", you are still invited!")
print("We have " + str(len(guests)) + " guests.")
del guests[0]
del guests[0]
print(guests)
